In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

In [ ]:
df = pd.read_csv(
    'https://raw.githubusercontent.com/Haroldgio28/Probabilidad_de_impago/main/data/case%202/Churn%20Modeling.csv'
    )

In [ ]:
df.head().T

0          1          2         3          4
RowNumber                1          2          3         4          5
CustomerId        15634602   15647311   15619304  15701354   15737888
Surname           Hargrave       Hill       Onio      Boni   Mitchell
CreditScore            619        608        502       699        850
Geography           France      Spain     France    France      Spain
Gender              Female     Female     Female    Female     Female
Age                     42         41         42        39         43
Tenure                   2          1          8         1          2
Balance                0.0   83807.86   159660.8       0.0  125510.82
NumOfProducts            1          1          3         2          1
HasCrCard                1          0          1         0          1
IsActiveMember           1          1          0         0          1
EstimatedSalary  101348.88  112542.58  113931.57  93826.63    79084.1
Exited                   1          0          1         0          0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [ ]:
cat_ord = []
cat_nomin = ['Geography','Gender','HasCrCard','IsActiveMember','Exited'] # 'Surname'
num_estand = []
num_norm = []
num_nada = []

In [ ]:
df.Surname.nunique()

2932

In [ ]:
df['Geography'].nunique()

3

In [ ]:
df['Gender'].nunique()

2

In [ ]:
X = df[cat_nomin]
X.head()

Geography  Gender  HasCrCard  IsActiveMember  Exited
0    France  Female          1               1       1
1     Spain  Female          0               1       0
2    France  Female          1               0       1
3    France  Female          0               0       0
4     Spain  Female          1               1       0

In [ ]:
# Instanciar una clase
encoder = OneHotEncoder(handle_unknown='ignore')

# encoder.fit(X)
# X_transform = encoder.transform(X)

X_transform=encoder.fit_transform(X)

In [ ]:
X_transform.toarray()[0]

array([1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1.])

In [ ]:
len(X_transform.toarray())

10000

In [ ]:
for i in cat_nomin:
  print(i," ",df[i].unique())

Geography   ['France' 'Spain' 'Germany']
Gender   ['Female' 'Male']
HasCrCard   [1 0]
IsActiveMember   [1 0]
Exited   [1 0]


In [ ]:
X_transform.toarray()[0]

array([1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1.])

In [ ]:
encoder.categories_

[array(['France', 'Germany', 'Spain'], dtype=object),
 array(['Female', 'Male'], dtype=object),
 array([0, 1]),
 array([0, 1]),
 array([0, 1])]

In [ ]:
X_transform.toarray()[0]

In [ ]:
encoder.inverse_transform([[1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1.]])

array([['France', 'Female', 1, 1, 1]], dtype=object)

In [ ]:
X

Geography  Gender  HasCrCard  IsActiveMember  Exited
0       France  Female          1               1       1
1        Spain  Female          0               1       0
2       France  Female          1               0       1
3       France  Female          0               0       0
4        Spain  Female          1               1       0
...        ...     ...        ...             ...     ...
9995    France    Male          1               0       0
9996    France    Male          1               1       0
9997    France  Female          0               1       1
9998   Germany    Male          1               0       1
9999    France  Female          1               0       0

[10000 rows x 5 columns]

In [ ]:
ord_enconder = OrdinalEncoder()
# ord_enconder.fit(X)
# X_transform_2 = ord_enconder.transform(X)
X_transform_2= ord_enconder.fit_transform(X)
X_transform_2

array([[0., 0., 1., 1., 1.],
       [2., 0., 0., 1., 0.],
       [0., 0., 1., 0., 1.],
       ...,
       [0., 0., 0., 1., 1.],
       [1., 1., 1., 0., 1.],
       [0., 0., 1., 0., 0.]])

In [ ]:
ord_enconder.inverse_transform([[1., 0., 1., 1., 1.]])

array([['Germany', 'Female', 1, 1, 1]], dtype=object)

In [ ]:
from sklearn.pipeline import make_pipeline, Pipeline
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

In [ ]:
cat_ord = ['IsActiveMember','Exited']
cat_nomin = ['Geography','Gender','HasCrCard'] # 'Surname'
num_estand = []
num_norm = []
num_nada = []

numeric_var = ['Age','Balance','EstimatedSalary' ]

X = df[cat_ord + cat_nomin + numeric_var]

In [ ]:
X.head()

IsActiveMember  Exited Geography  Gender  HasCrCard  Age    Balance  \
0               1       1    France  Female          1   42       0.00   
1               1       0     Spain  Female          0   41   83807.86   
2               0       1    France  Female          1   42  159660.80   
3               0       0    France  Female          0   39       0.00   
4               1       0     Spain  Female          1   43  125510.82   

   EstimatedSalary  
0        101348.88  
1        112542.58  
2        113931.57  
3         93826.63  
4         79084.10

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   IsActiveMember   10000 non-null  int64  
 1   Exited           10000 non-null  int64  
 2   Geography        10000 non-null  object 
 3   Gender           10000 non-null  object 
 4   HasCrCard        10000 non-null  int64  
 5   Age              10000 non-null  int64  
 6   Balance          10000 non-null  float64
 7   EstimatedSalary  10000 non-null  float64
dtypes: float64(2), int64(4), object(2)
memory usage: 625.1+ KB


In [ ]:
pipeline_categoricas_nom = Pipeline(
    [('imputador', SimpleImputer(strategy = 'most_frequent')),
     ('dummy',OneHotEncoder(handle_unknown='ignore'))]
)

pipeline_categoricas_nom

Pipeline(steps=[('imputador', SimpleImputer(strategy='most_frequent')),
                ('dummy', OneHotEncoder(handle_unknown='ignore'))])

In [ ]:
pipeline_categoricas_ord = Pipeline(
    [('imputador', SimpleImputer(strategy = 'most_frequent')),
     ('ordinal',OrdinalEncoder())]
)

pipeline_categoricas_ord

Pipeline(steps=[('imputador', SimpleImputer(strategy='most_frequent')),
                ('ordinal', OrdinalEncoder())])

In [ ]:
# Pipeline para variables numéricas
pipeline_numerico = Pipeline(
    [('imputador', SimpleImputer(strategy = 'median')),
     ('escalador', StandardScaler())]
     )

pipeline_numerico

Pipeline(steps=[('imputador', SimpleImputer(strategy='median')),
                ('escalador', StandardScaler())])

In [ ]:
procesador = ColumnTransformer(
    [('codificador ordinal',pipeline_categoricas_ord,cat_ord),
     ('codificador nominal',pipeline_categoricas_nom,cat_nomin),
     ('codificador numerico',pipeline_numerico,numeric_var)]
)

procesador

ColumnTransformer(transformers=[('codificador ordinal',
                                 Pipeline(steps=[('imputador',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('ordinal',
                                                  OrdinalEncoder())]),
                                 ['IsActiveMember', 'Exited']),
                                ('codificador nominal',
                                 Pipeline(steps=[('imputador',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('dummy',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['Geography', 'Gender', 'HasCrCard']),
                                ('codificador numerico',
                                 Pipeline(steps=[('imputador',
                                                  SimpleImputer(strategy='median')),
                                                 ('escalador',
                                                  StandardScaler())]),
                                 ['Age', 'Balance', 'EstimatedSalary'])])

In [ ]:
X

IsActiveMember  Exited Geography  Gender  HasCrCard  Age    Balance  \
0                  1       1    France  Female          1   42       0.00   
1                  1       0     Spain  Female          0   41   83807.86   
2                  0       1    France  Female          1   42  159660.80   
3                  0       0    France  Female          0   39       0.00   
4                  1       0     Spain  Female          1   43  125510.82   
...              ...     ...       ...     ...        ...  ...        ...   
9995               0       0    France    Male          1   39       0.00   
9996               1       0    France    Male          1   35   57369.61   
9997               1       1    France  Female          0   36       0.00   
9998               0       1   Germany    Male          1   42   75075.31   
9999               0       0    France  Female          1   28  130142.79   

      EstimatedSalary  
0           101348.88  
1           112542.58  
2           113931.57  
3            93826.63  
4            79084.10  
...               ...  
9995         96270.64  
9996        101699.77  
9997         42085.58  
9998         92888.52  
9999         38190.78  

[10000 rows x 8 columns]

In [ ]:
procesador.fit(X)
X_transform = procesador.transform(X)
X_transform.shape

(10000, 12)

In [ ]:
X.head(1)

IsActiveMember  Exited Geography  Gender  HasCrCard  Age  Balance  \
0               1       1    France  Female          1   42      0.0   

   EstimatedSalary  
0        101348.88

In [ ]:
X_transform[0]

array([ 1.        ,  1.        ,  1.        ,  0.        ,  0.        ,
        1.        ,  0.        ,  0.        ,  1.        ,  0.29351742,
       -1.22584767,  0.02188649])

In [ ]:
# Ejemplo de uso
# pipeline_categoricas_nom.fit_transform(X).toarray()

# ejemplo = ['France',np.nan,1,0,0]
# pipeline_categoricas_nom.transform([ejemplo]).toarray()

## Pipeline de procesamiento de variable numéricas

In [ ]:
from sklearn.pipeline import make_pipeline, Pipeline
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler, MinMaxScaler, OrdinalEncoder

In [ ]:
numeric_var = ['Age','Balance','EstimatedSalary' ]

In [ ]:
# Pipeline para variables numéricas
pipeline_numerico = Pipeline(
    [('imputador', SimpleImputer(strategy = 'median')),
     ('escalador', StandardScaler())]
     )

pipeline_numerico

Pipeline(steps=[('imputador', SimpleImputer(strategy='median')),
                ('escalador', StandardScaler())])

In [ ]:
df.info()

In [ ]:
pipeline_numerico.fit_transform(df[numeric_var])

array([[ 0.29351742, -1.22584767,  0.02188649],
       [ 0.19816383,  0.11735002,  0.21653375],
       [ 0.29351742,  1.33305335,  0.2406869 ],
       ...,
       [-0.27860412, -1.22584767, -1.00864308],
       [ 0.29351742, -0.02260751, -0.12523071],
       [-1.04143285,  0.85996499, -1.07636976]])

In [ ]:
import numpy as np
from sklearn.preprocessing import OrdinalEncoder

# Datos categóricos
data = np.array([
    ['bajo', 'azul', 'triangulo'],
    ['alto', 'rojo', 'circulo'],
    ['mediano', 'verde', 'circulo'],
    ['alto', 'rojo', 'cuadrado']
])

# Especificar el orden de las categorías para cada característica
categories = [
    ['bajo', 'mediano', 'alto'],         # Orden para la primera característica
    ['azul', 'rojo', 'verde'],           # Orden para la segunda característica
    ['triangulo', 'circulo', 'cuadrado'] # Orden para la tercera característica
]

# Crear el codificador ordinal con las categorías especificadas
encoder = OrdinalEncoder(categories=categories)

# Ajustar el codificador a los datos y transformarlos
encoded_data = encoder.fit_transform(data)

# Mostrar los datos originales y codificados
print("Datos originales:")
print(data)
print("\nDatos codificados:")
print(encoded_data)

Datos originales:
[['bajo' 'azul' 'triangulo']
 ['alto' 'rojo' 'circulo']
 ['mediano' 'verde' 'circulo']
 ['alto' 'rojo' 'cuadrado']]

Datos codificados:
[[0. 0. 0.]
 [2. 1. 1.]
 [1. 2. 1.]
 [2. 1. 2.]]


In [ ]:
categories = [
    ['bajo', 'mediano', 'alto'],   # Orden para la primera característica
    ['mediano', 'alto', 'bajo'],   # Orden para la segunda característica
    ['alto', 'mediano', 'bajo']    # Orden para la tercera característica
]

In [ ]:
ciudades = pd.DataFrame(['Bogota','Medellin','Cali','Cartagena','Cartagena','Pasto','Barranquilla'])
ciudades

0
0        Bogota
1      Medellin
2          Cali
3     Cartagena
4     Cartagena
5         Pasto
6  Barranquilla

In [ ]:
# Instanciar una clase
encoder = OneHotEncoder(handle_unknown='ignore')
# encoder = OneHotEncoder()

In [ ]:
encoder.fit(ciudades)

OneHotEncoder(handle_unknown='ignore')

In [ ]:
encoder.categories_

[array(['Barranquilla', 'Bogota', 'Cali', 'Cartagena', 'Medellin', 'Pasto'],
       dtype=object)]

In [ ]:
encoder.fit_transform(ciudades).toarray()

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0.]])

In [ ]:
encoder.transform([['Ibague']]).toarray()

array([[0., 0., 0., 0., 0., 0.]])