### Clase sobre numpy!

**1. Introducción a NumPy**

* Definición: NumPy (Numerical Python) es una librería para el lenguaje de programación Python, que se utiliza para trabajar con matrices y arreglos multidimensionales. Proporciona funciones matemáticas de alto rendimiento y herramientas para trabajar con estos datos.

**2. Instalación de NumPy**

In [1]:
# Para instalar NumPy, usa el siguiente comando en tu terminal o consola:
# python installs packages

!pip install numpy

**3. Importamos NumPy**

In [3]:
#Importamos la librería
#Usamos el alias np

import numpy as np

**4. Construcción de arreglos (vectores, o matrices)**

In [ ]:
#En numpy el tipo de dato primordial son los arreglos o arrays
#Estos funcionan como matrices o vectores, según sus dimensiones

In [ ]:
# Creación de un arreglo unidimensional (vector)
# tuple([1,2,3])

arr_1d = np.array([1, 2, 3, 4, 5])

print(arr_1d)
print(type(arr_1d))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# Creación de un arreglo bidimensional (matriz)

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]
                   ]
                  )
print(arr_2d)
print(type(arr_2d))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [ ]:
#Los arreglos son similares a las listas
#Podemos acceder a ellos a través de los índices
print("arr_1d: ", arr_1d)
print("Primer elemento del vector arr_1d: ", arr_1d[0]) #Primer elemento del vector arr_1d
print("Del primero al tercer elemento del vector arr_1d: ", arr_1d[:3]) #Del primero al tercer elemento del vector arr_1d

print("arr_2d: ", arr_2d)
print("Tercer elemento del segundo arreglo de la matriz arr_2d: ", arr_2d[1][:2]) #Tercer elemento del segundo arreglo de la matriz arr_2d

arr_1d:  [1 2 3 4 5]
Primer elemento del vector arr_1d:  1
Del primero al tercer elemento del vector arr_1d:  [1 2 3]
arr_2d:  [[1 2 3]
 [4 5 6]]
Tercer elemento del segundo arreglo de la matriz arr_2d:  [4 5]


###### **5. Funcionalidades básicas**

In [ ]:
dir(arr_1d)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [ ]:
#5.1 Atributos de los arreglos
# .append()
print(arr_1d.ndim)  # Número de dimensiones
print(arr_2d.ndim)  # Número de dimensiones

print('Shape: ', arr_2d.shape) # Forma del arreglo
print(arr_2d)

print(arr_2d.size)  # Número total de elementos

1
2
Shape:  (2, 3)
[[1 2 3]
 [4 5 6]]
6


In [ ]:
np.array([[1,2,3], [4,5]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
#5.2 Creación de arreglos especiales
#Arreglo de ceros
zeros = np.zeros((3, 5))
print(zeros)

# Arreglo de unos
ones = np.ones((2, 4))
print(ones)

# Arreglo con valores constantes
full = np.full((2, 3), -1)
print(full)

# Arreglo identidad
identity = np.eye(4)
print(identity)

# Arreglo con valores aleatorios
random = np.random.random((4, 5))
print(random)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[-1 -1 -1]
 [-1 -1 -1]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.67354349 0.68242751 0.29297663 0.35771766 0.20077379]
 [0.42205371 0.937669   0.77921078 0.82743534 0.45672418]
 [0.19554587 0.74354608 0.87932176 0.4910601  0.84275117]
 [0.69892511 0.10887145 0.91701203 0.38194229 0.15494919]]


In [ ]:
# Crear un vector
vector = np.arange(1, 11, 1)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
for i in np.arange(1,11,1):
  print(i, i % 2)

1 1
2 0
3 1
4 0
5 1
6 0
7 1
8 0
9 1
10 0


###### **6. Operaciones Matemáticas**

In [ ]:
# 6.1 Operaciones elementales
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Suma
print(a + b)

# # Resta
print(a - b)

# # Multiplicación
print(a * b)

# # División
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
# Qué pasa si lo intento con una lista?
list_a = [1, 2, 3]
list_b = [4, 5, 6]

print(list_a + list_b)

[1, 2, 3, 4, 5, 6]


In [ ]:
# con un escalar
print(a)
a * 3

[1 2 3]


array([3, 6, 9])

In [ ]:
a ** 2

array([1, 4, 9])

In [ ]:
# Advertencia
'aaa' * 3

'aaaaaaaaa'

###### Una de las características más importantes de numpy!
**Las operaciones vectorizadas** se basan en el concepto de vectorización, que es el proceso de convertir una operación escalar (una que funciona en un solo valor) en una operación vectorial (una que trabaja en una colección de valores).

In [ ]:
# 6.2 Funciones universales

# Redondear
print("Pi redondeado: ", np.round(np.pi, 4))
print("Lista redondeada: ", np.round([0.1234, 1.564, 9.8483, 7], 2))

print("Variable a: ", a)
# Raíz cuadrada
print("Raíz cuadrada de elementos en a: ", np.round(np.sqrt(a), 2))

# Potencia
print("Potencia de elementos en a: ", np.power(a, 2))

# Seno
print("Seno de a: ", np.sin(a))

# Coseno
print("Coseno de a: ", np.cos(a))

# Logaritmo
print("Logaritmo de a: ",np.log(a))

Pi redondeado:  3.1416
Lista redondeada:  [0.12 1.56 9.85 7.  ]
Variable a:  [1 2 3]
Raíz cuadrada de elementos en a:  [1.   1.41 1.73]
Potencia de elementos en a:  [1 4 9]
Seno de a:  [0.84147098 0.90929743 0.14112001]
Coseno de a:  [ 0.54030231 -0.41614684 -0.9899925 ]
Logaritmo de a:  [0.         0.69314718 1.09861229]


In [ ]:
# Qué pasará si intentamos usar la función "round" para una lista o en un arreglo de numpy?
# np.round(np.array([0.1234, 1.564, 9.8483, 7]), 2)

lista = [0.1234, 1.564, 9.8483, 7]
lista_redondeada = []

for i in lista:
  lista_redondeada.append(round(i, 2))

print(lista)
print(lista_redondeada)

[0.1234, 1.564, 9.8483, 7]
[0.12, 1.56, 9.85, 7]


In [ ]:
# Encontrar el máximo entre los elementos de dos estrucutras de datos, por índice
a = np.array([8, 2, 3])
b = np.array([4, 5, 6])

print('Máximo entre las dos listas:', np.maximum(a, b))
print('Mínimo entre las dos listas:', np.minimum(a, b))

# También existe np.minimum!
# Qué pasa si lo hacemos con max()?

Máximo entre las dos listas: [8 5 6]
Mínimo entre las dos listas: [4 2 3]


In [ ]:
# El máximo o mínimo dentro de una sola lista
print(np.max(a))
print(np.min(a))

8
2


In [ ]:
# Usamos np.where para applicar condicionales a nuestras listas, sin usar loops!
# np.where(condición, valor si se cumple, valor si no se cumple)

arr = np.array([1, 2, 3, 4, 5])

# np.where(arr < 3, '< 3', '>= 3')

print(np.where(arr < 3,
               '< 3',
               '>= 3')
      )

arr_where = np.where(arr < 3, '< 3', '>= 3')
print(type(arr_where))

['< 3' '< 3' '>= 3' '>= 3' '>= 3']
<class 'numpy.ndarray'>


In [ ]:
# Podemos usar np.where anidados, similar a los condicionales if..elif....else:
nested_where = np.where(arr < 3,
                        '< 3',
                        np.where(arr == 3,
                                 '== 3',
                                 '> 3')
                        )

# nested_where = np.where(arr < 3,'< 3', np.where(arr == 3, '== 3','> 3'))
print(arr)
print(nested_where)

[1 2 3 4 5]
['< 3' '< 3' '== 3' '> 3' '> 3']


In [ ]:
# ¿Cómo se vería con condicionales y loops?
print(arr)
arr_transformed = []

for i in arr:
  if i < 3:
    resultado = '< 3'
  elif i == 3:
    resultado = '== 3'
  else:
    resultado = '> 3'

  arr_transformed.append(resultado)

print(arr_transformed)

[1 2 3 4 5]
['< 3', '< 3', '== 3', '> 3', '> 3']


######**7. Manipulación de arreglos**

In [ ]:
#Cambiar las dimensiones del arreglo - cambiar la forma
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)
print(arr.shape)
print(arr.size)

reshaped = arr.reshape((-1, 1))

print(arr)
print(reshaped)
print(reshaped.shape)
print(reshaped.size)

[1 2 3 4 5 6]
(6,)
6
[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)
6


In [ ]:
arr = np.array([[1, 2, 3, 4, 5, 6],
               [7, 8, 9, 10, 11, 12]
                ]
               )
# print(arr.shape)
print(arr.size)

reshaped = arr.reshape((-1, 1))
# print(arr)
print(reshaped)
print(reshaped.shape)
print(reshaped.size)

12
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
(12, 1)
12


In [ ]:
a = np.array([[1, 2], # 5
              [3, 4]]) # 6

b = np.array([[5, 6]])

# Concatenar a y b
print("Concatenar:\n", np.concatenate((a, b), axis=0)) #axis = 0 vertical, axis = 1 horizontal
print("Concatenar:\n", np.concatenate((a, b.T), axis=1)) #axis = 0 vertical, axis = 1 horizontal

# Apilar verticalmente
print("Apilar verticalmente:\n", np.vstack((a, b)))

# # # Apilar horizontalmente
print("Apilar horizontalmente:\n", np.hstack((a, b.T)))  # b.T es la transpuesta de b

Concatenar:
 [[1 2]
 [3 4]
 [5 6]]
Concatenar:
 [[1 2 5]
 [3 4 6]]
Apilar verticalmente:
 [[1 2]
 [3 4]
 [5 6]]
Apilar horizontalmente:
 [[1 2 5]
 [3 4 6]]


In [ ]:
b.T

array([[5],
       [6]])

In [ ]:
b = np.array([[5, 6]]).reshape((-1, 1))
print("Concatenar:\n", np.concatenate((a, b), axis=1))

Concatenar:
 [[1 2 5]
 [3 4 6]]


In [ ]:
# Guardar arreglo en un archivo
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]]
               )

np.save('array.npy', arr)

In [ ]:
# Cargar arreglo desde un archivo
loaded_arr = np.load('array.npy')
print(loaded_arr)

######**10. Ejemplos prácticos**

In [ ]:
#10.1 Cálculo de la media, mediana y desviación estándar
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print("Media, Promedio:", np.mean(data))
print("Mediana:", np.median(data))
print("Desviación estándar:", np.round(np.std(data),2))

Media, Promedio: 5.0
Mediana: 5.0
Desviación estándar: 2.58


In [ ]:
#10.2 Operaciones con matrices
mat1 = np.array([[1, 2],
                 [3, 4]])
mat2 = np.array([[5, 6],
                 [7, 8]])

# Producto punto
print(np.dot(mat1, mat2))

# Transpuesta
# También -> mat1.T
print(np.transpose(mat1))

# Inversa (si existe)
print(np.linalg.inv(mat1))

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [5]:
#10.3 Filtrar datos de un array

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Encontrar los valores que son mayores a 5
bool_arr = arr > 5
print(arr > 5)

# Filtrar valores mayores que 5
# arr[bool_arr]
print(arr[bool_arr])

[False False False False False  True  True  True  True]
[6 7 8 9]


In [ ]:
# Revisemos el array arr, qué vemos?
# Tenemos solo los valores del filtro anterior?

In [ ]:
for i in arr:
  if i > 5:
    print('Menor a 5')
  else:
    print('Condición no se cumple')

Menor a 5 y mayor a 8
Menor a 5 y mayor a 8
Menor a 5 y mayor a 8
Menor a 5 y mayor a 8
Condición no se cumple
Condición no se cumple
Condición no se cumple
Condición no se cumple
Menor a 5 y mayor a 8


In [8]:
# Utilizar condicionales and (&) y or (|)
#arr[(arr > 5) & (arr < 8)]
#arr[(arr < 5) | (arr > 8)]

array([1, 2, 3, 4, 9])

In [ ]:
print(arr)

for i in arr:
  if i < 5 or i > 8:
    print('Menor a 5 o mayor a 8')
  else:
    print('Condición no se cumple')

[1 2 3 4 5 6 7 8 9]
Menor a 5 o mayor a 8
Menor a 5 o mayor a 8
Menor a 5 o mayor a 8
Menor a 5 o mayor a 8
Condición no se cumple
Condición no se cumple
Condición no se cumple
Condición no se cumple
Menor a 5 o mayor a 8


In [10]:
# and -> &
# or -> |
print(arr > 2)
print(arr < 8)
print((arr > 2) * (arr < 8))
arr[(arr > 2) & (arr < 8)]

[False False  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True False False]
[False False  True  True  True  True  True False False]


array([3, 4, 5, 6, 7])

In [11]:
arr_filtrado = arr[(arr < 5) | (arr > 8)]
print(arr_filtrado)

[1 2 3 4 9]


###### **12. Recursos adicionales**

Documentación oficial de NumPy:

https://numpy.org/doc/2.0/user/absolute_beginners.html

Tutoriales y guías: Recursos en línea y videos para profundizar en NumPy.

https://www.freecodecamp.org/learn/data-analysis-with-python/#numpy

### **Ejercicios!**

###### **Ejercicio 1: Manipulación de Arreglos**
* Objetivo: Crear, manipular y aplicar operaciones básicas a arreglos.

In [ ]:
# Instrucciones:

# 1. Crea un arreglo unidimensional con los números del 1 al 10.
# 2. Cambia la forma del arreglo para que sea una matriz de 2x5.
# 3. Encuentra la suma de todos los elementos de la matriz.
# 4. Encuentra el valor máximo y mínimo en la matriz.
# 5. Calcula la media y la desviación estándar de los elementos de la matriz.

* Solución

In [15]:
# @title
import numpy as np

# Paso 1
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Paso 2
mat = arr.reshape((2, 5))
print("Matriz 2x5:")
print(mat)

# Paso 3
suma = np.sum(mat)
print("Suma de todos los elementos:", suma)

# Paso 4
max_val = np.max(mat)
min_val = np.min(mat)
print("Valor máximo:", max_val)
print("Valor mínimo:", min_val)

# Paso 5
media = np.mean(mat)
print("Media:", media)

desviacion_estandar = np.std(mat)
print('Desviación estándar:', np.round(desviacion_estandar, 2))

Matriz 2x5:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Suma de todos los elementos: 55
Valor máximo: 10
Valor mínimo: 1
Media: 5.5
Desviación estándar: 2.87


###### **Ejercicio 2: Operaciones con Matrices**
* Objetivo: Realizar operaciones matemáticas avanzadas con matrices.

In [ ]:
# Instrucciones:

# 1. Crea dos matrices de 2x2 con números del 1 al 4 y del 5 al 8 respectivamente.
# 2. Realiza la multiplicación de las dos matrices.
# 3. Encuentra la transpuesta de la primera matriz.

* Solución

In [16]:
# @title
import numpy as np

# Paso 1
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
print("Matriz 1:")
print(mat1)
print("Matriz 2:")
print(mat2)

# Paso 2
producto = np.dot(mat1, mat2)
print("Producto de las matrices:")
print(producto)

# Paso 3
transpuesta = np.transpose(mat1)
print("Transpuesta de la matriz 1:")
print(transpuesta)

Matriz 1:
[[1 2]
 [3 4]]
Matriz 2:
[[5 6]
 [7 8]]
Producto de las matrices:
[[19 22]
 [43 50]]
Transpuesta de la matriz 1:
[[1 3]
 [2 4]]


######**Ejercicio 3: Análisis de Datos**
* Objetivo: Utilizar NumPy para realizar análisis de datos estadísticos.

In [ ]:
# Instrucciones:

# 1. Crea un arreglo con los números del 1 al 100.
# 2. Calcula la media y la desviación estándar del arreglo.
# 3. Filtra los valores del arreglo que son mayores que 50.
# 4. Encuentra el valor máximo y mínimo del arreglo filtrado.

* Solución

In [17]:
# @title
import numpy as np

# Paso 1
data = np.array(range(1, 101))

# Paso 2
media = np.mean(data)
std_dev = np.std(data)
print("Media:", media)
print("Desviación estándar:", std_dev)

# Paso 3
valores_mayores_50 = data[data > 50]
print("Valores mayores que 50:", valores_mayores_50)

# Paso 4
max_val = np.max(valores_mayores_50)
min_val = np.min(valores_mayores_50)
print("Valor máximo del arreglo filtrado:", max_val)
print("Valor mínimo del arreglo filtrado:", min_val)

Media: 50.5
Desviación estándar: 28.86607004772212
Valores mayores que 50: [ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]
Valor máximo del arreglo filtrado: 100
Valor mínimo del arreglo filtrado: 51
